no-tests = true
output = "models"
wipe = false

[mysql]
dbname = "DataPlatformMastersAndTransactionsMysqlKube"
host = "XXXXXXXXXX"
port = 30010
user = "XXXXXXXXXX"
pass = "XXXXXXXXXX"
sslmode = "false"
