// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SapProductMasterSalesTaxDatum is an object representing the database table.
type SapProductMasterSalesTaxDatum struct {
	Product           string      `boil:"Product" json:"Product" toml:"Product" yaml:"Product"`
	Country           string      `boil:"Country" json:"Country" toml:"Country" yaml:"Country"`
	TaxCategory       string      `boil:"TaxCategory" json:"TaxCategory" toml:"TaxCategory" yaml:"TaxCategory"`
	TaxClassification null.String `boil:"TaxClassification" json:"TaxClassification,omitempty" toml:"TaxClassification" yaml:"TaxClassification,omitempty"`

	R *sapProductMasterSalesTaxDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L sapProductMasterSalesTaxDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SapProductMasterSalesTaxDatumColumns = struct {
	Product           string
	Country           string
	TaxCategory       string
	TaxClassification string
}{
	Product:           "Product",
	Country:           "Country",
	TaxCategory:       "TaxCategory",
	TaxClassification: "TaxClassification",
}

var SapProductMasterSalesTaxDatumTableColumns = struct {
	Product           string
	Country           string
	TaxCategory       string
	TaxClassification string
}{
	Product:           "sap_product_master_sales_tax_data.Product",
	Country:           "sap_product_master_sales_tax_data.Country",
	TaxCategory:       "sap_product_master_sales_tax_data.TaxCategory",
	TaxClassification: "sap_product_master_sales_tax_data.TaxClassification",
}

// Generated where

var SapProductMasterSalesTaxDatumWhere = struct {
	Product           whereHelperstring
	Country           whereHelperstring
	TaxCategory       whereHelperstring
	TaxClassification whereHelpernull_String
}{
	Product:           whereHelperstring{field: "`sap_product_master_sales_tax_data`.`Product`"},
	Country:           whereHelperstring{field: "`sap_product_master_sales_tax_data`.`Country`"},
	TaxCategory:       whereHelperstring{field: "`sap_product_master_sales_tax_data`.`TaxCategory`"},
	TaxClassification: whereHelpernull_String{field: "`sap_product_master_sales_tax_data`.`TaxClassification`"},
}

// SapProductMasterSalesTaxDatumRels is where relationship names are stored.
var SapProductMasterSalesTaxDatumRels = struct {
	ProductSapProductMasterGeneralDatum string
}{
	ProductSapProductMasterGeneralDatum: "ProductSapProductMasterGeneralDatum",
}

// sapProductMasterSalesTaxDatumR is where relationships are stored.
type sapProductMasterSalesTaxDatumR struct {
	ProductSapProductMasterGeneralDatum *SapProductMasterGeneralDatum `boil:"ProductSapProductMasterGeneralDatum" json:"ProductSapProductMasterGeneralDatum" toml:"ProductSapProductMasterGeneralDatum" yaml:"ProductSapProductMasterGeneralDatum"`
}

// NewStruct creates a new relationship struct
func (*sapProductMasterSalesTaxDatumR) NewStruct() *sapProductMasterSalesTaxDatumR {
	return &sapProductMasterSalesTaxDatumR{}
}

// sapProductMasterSalesTaxDatumL is where Load methods for each relationship are stored.
type sapProductMasterSalesTaxDatumL struct{}

var (
	sapProductMasterSalesTaxDatumAllColumns            = []string{"Product", "Country", "TaxCategory", "TaxClassification"}
	sapProductMasterSalesTaxDatumColumnsWithoutDefault = []string{"Product", "Country", "TaxCategory", "TaxClassification"}
	sapProductMasterSalesTaxDatumColumnsWithDefault    = []string{}
	sapProductMasterSalesTaxDatumPrimaryKeyColumns     = []string{"Product", "Country", "TaxCategory"}
)

type (
	// SapProductMasterSalesTaxDatumSlice is an alias for a slice of pointers to SapProductMasterSalesTaxDatum.
	// This should almost always be used instead of []SapProductMasterSalesTaxDatum.
	SapProductMasterSalesTaxDatumSlice []*SapProductMasterSalesTaxDatum
	// SapProductMasterSalesTaxDatumHook is the signature for custom SapProductMasterSalesTaxDatum hook methods
	SapProductMasterSalesTaxDatumHook func(context.Context, boil.ContextExecutor, *SapProductMasterSalesTaxDatum) error

	sapProductMasterSalesTaxDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	sapProductMasterSalesTaxDatumType                 = reflect.TypeOf(&SapProductMasterSalesTaxDatum{})
	sapProductMasterSalesTaxDatumMapping              = queries.MakeStructMapping(sapProductMasterSalesTaxDatumType)
	sapProductMasterSalesTaxDatumPrimaryKeyMapping, _ = queries.BindMapping(sapProductMasterSalesTaxDatumType, sapProductMasterSalesTaxDatumMapping, sapProductMasterSalesTaxDatumPrimaryKeyColumns)
	sapProductMasterSalesTaxDatumInsertCacheMut       sync.RWMutex
	sapProductMasterSalesTaxDatumInsertCache          = make(map[string]insertCache)
	sapProductMasterSalesTaxDatumUpdateCacheMut       sync.RWMutex
	sapProductMasterSalesTaxDatumUpdateCache          = make(map[string]updateCache)
	sapProductMasterSalesTaxDatumUpsertCacheMut       sync.RWMutex
	sapProductMasterSalesTaxDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var sapProductMasterSalesTaxDatumBeforeInsertHooks []SapProductMasterSalesTaxDatumHook
var sapProductMasterSalesTaxDatumBeforeUpdateHooks []SapProductMasterSalesTaxDatumHook
var sapProductMasterSalesTaxDatumBeforeDeleteHooks []SapProductMasterSalesTaxDatumHook
var sapProductMasterSalesTaxDatumBeforeUpsertHooks []SapProductMasterSalesTaxDatumHook

var sapProductMasterSalesTaxDatumAfterInsertHooks []SapProductMasterSalesTaxDatumHook
var sapProductMasterSalesTaxDatumAfterSelectHooks []SapProductMasterSalesTaxDatumHook
var sapProductMasterSalesTaxDatumAfterUpdateHooks []SapProductMasterSalesTaxDatumHook
var sapProductMasterSalesTaxDatumAfterDeleteHooks []SapProductMasterSalesTaxDatumHook
var sapProductMasterSalesTaxDatumAfterUpsertHooks []SapProductMasterSalesTaxDatumHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SapProductMasterSalesTaxDatum) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterSalesTaxDatumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SapProductMasterSalesTaxDatum) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterSalesTaxDatumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SapProductMasterSalesTaxDatum) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterSalesTaxDatumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SapProductMasterSalesTaxDatum) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterSalesTaxDatumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SapProductMasterSalesTaxDatum) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterSalesTaxDatumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SapProductMasterSalesTaxDatum) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterSalesTaxDatumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SapProductMasterSalesTaxDatum) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterSalesTaxDatumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SapProductMasterSalesTaxDatum) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterSalesTaxDatumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SapProductMasterSalesTaxDatum) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterSalesTaxDatumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSapProductMasterSalesTaxDatumHook registers your hook function for all future operations.
func AddSapProductMasterSalesTaxDatumHook(hookPoint boil.HookPoint, sapProductMasterSalesTaxDatumHook SapProductMasterSalesTaxDatumHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		sapProductMasterSalesTaxDatumBeforeInsertHooks = append(sapProductMasterSalesTaxDatumBeforeInsertHooks, sapProductMasterSalesTaxDatumHook)
	case boil.BeforeUpdateHook:
		sapProductMasterSalesTaxDatumBeforeUpdateHooks = append(sapProductMasterSalesTaxDatumBeforeUpdateHooks, sapProductMasterSalesTaxDatumHook)
	case boil.BeforeDeleteHook:
		sapProductMasterSalesTaxDatumBeforeDeleteHooks = append(sapProductMasterSalesTaxDatumBeforeDeleteHooks, sapProductMasterSalesTaxDatumHook)
	case boil.BeforeUpsertHook:
		sapProductMasterSalesTaxDatumBeforeUpsertHooks = append(sapProductMasterSalesTaxDatumBeforeUpsertHooks, sapProductMasterSalesTaxDatumHook)
	case boil.AfterInsertHook:
		sapProductMasterSalesTaxDatumAfterInsertHooks = append(sapProductMasterSalesTaxDatumAfterInsertHooks, sapProductMasterSalesTaxDatumHook)
	case boil.AfterSelectHook:
		sapProductMasterSalesTaxDatumAfterSelectHooks = append(sapProductMasterSalesTaxDatumAfterSelectHooks, sapProductMasterSalesTaxDatumHook)
	case boil.AfterUpdateHook:
		sapProductMasterSalesTaxDatumAfterUpdateHooks = append(sapProductMasterSalesTaxDatumAfterUpdateHooks, sapProductMasterSalesTaxDatumHook)
	case boil.AfterDeleteHook:
		sapProductMasterSalesTaxDatumAfterDeleteHooks = append(sapProductMasterSalesTaxDatumAfterDeleteHooks, sapProductMasterSalesTaxDatumHook)
	case boil.AfterUpsertHook:
		sapProductMasterSalesTaxDatumAfterUpsertHooks = append(sapProductMasterSalesTaxDatumAfterUpsertHooks, sapProductMasterSalesTaxDatumHook)
	}
}

// One returns a single sapProductMasterSalesTaxDatum record from the query.
func (q sapProductMasterSalesTaxDatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SapProductMasterSalesTaxDatum, error) {
	o := &SapProductMasterSalesTaxDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for sap_product_master_sales_tax_data")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SapProductMasterSalesTaxDatum records from the query.
func (q sapProductMasterSalesTaxDatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (SapProductMasterSalesTaxDatumSlice, error) {
	var o []*SapProductMasterSalesTaxDatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SapProductMasterSalesTaxDatum slice")
	}

	if len(sapProductMasterSalesTaxDatumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SapProductMasterSalesTaxDatum records in the query.
func (q sapProductMasterSalesTaxDatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count sap_product_master_sales_tax_data rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q sapProductMasterSalesTaxDatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if sap_product_master_sales_tax_data exists")
	}

	return count > 0, nil
}

// ProductSapProductMasterGeneralDatum pointed to by the foreign key.
func (o *SapProductMasterSalesTaxDatum) ProductSapProductMasterGeneralDatum(mods ...qm.QueryMod) sapProductMasterGeneralDatumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`Product` = ?", o.Product),
	}

	queryMods = append(queryMods, mods...)

	query := SapProductMasterGeneralData(queryMods...)
	queries.SetFrom(query.Query, "`sap_product_master_general_data`")

	return query
}

// LoadProductSapProductMasterGeneralDatum allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (sapProductMasterSalesTaxDatumL) LoadProductSapProductMasterGeneralDatum(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSapProductMasterSalesTaxDatum interface{}, mods queries.Applicator) error {
	var slice []*SapProductMasterSalesTaxDatum
	var object *SapProductMasterSalesTaxDatum

	if singular {
		object = maybeSapProductMasterSalesTaxDatum.(*SapProductMasterSalesTaxDatum)
	} else {
		slice = *maybeSapProductMasterSalesTaxDatum.(*[]*SapProductMasterSalesTaxDatum)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &sapProductMasterSalesTaxDatumR{}
		}
		args = append(args, object.Product)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sapProductMasterSalesTaxDatumR{}
			}

			for _, a := range args {
				if a == obj.Product {
					continue Outer
				}
			}

			args = append(args, obj.Product)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`sap_product_master_general_data`),
		qm.WhereIn(`sap_product_master_general_data.Product in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SapProductMasterGeneralDatum")
	}

	var resultSlice []*SapProductMasterGeneralDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SapProductMasterGeneralDatum")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for sap_product_master_general_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sap_product_master_general_data")
	}

	if len(sapProductMasterSalesTaxDatumAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ProductSapProductMasterGeneralDatum = foreign
		if foreign.R == nil {
			foreign.R = &sapProductMasterGeneralDatumR{}
		}
		foreign.R.ProductSapProductMasterSalesTaxData = append(foreign.R.ProductSapProductMasterSalesTaxData, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Product == foreign.Product {
				local.R.ProductSapProductMasterGeneralDatum = foreign
				if foreign.R == nil {
					foreign.R = &sapProductMasterGeneralDatumR{}
				}
				foreign.R.ProductSapProductMasterSalesTaxData = append(foreign.R.ProductSapProductMasterSalesTaxData, local)
				break
			}
		}
	}

	return nil
}

// SetProductSapProductMasterGeneralDatum of the sapProductMasterSalesTaxDatum to the related item.
// Sets o.R.ProductSapProductMasterGeneralDatum to related.
// Adds o to related.R.ProductSapProductMasterSalesTaxData.
func (o *SapProductMasterSalesTaxDatum) SetProductSapProductMasterGeneralDatum(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SapProductMasterGeneralDatum) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `sap_product_master_sales_tax_data` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"Product"}),
		strmangle.WhereClause("`", "`", 0, sapProductMasterSalesTaxDatumPrimaryKeyColumns),
	)
	values := []interface{}{related.Product, o.Product, o.Country, o.TaxCategory}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.Product = related.Product
	if o.R == nil {
		o.R = &sapProductMasterSalesTaxDatumR{
			ProductSapProductMasterGeneralDatum: related,
		}
	} else {
		o.R.ProductSapProductMasterGeneralDatum = related
	}

	if related.R == nil {
		related.R = &sapProductMasterGeneralDatumR{
			ProductSapProductMasterSalesTaxData: SapProductMasterSalesTaxDatumSlice{o},
		}
	} else {
		related.R.ProductSapProductMasterSalesTaxData = append(related.R.ProductSapProductMasterSalesTaxData, o)
	}

	return nil
}

// SapProductMasterSalesTaxData retrieves all the records using an executor.
func SapProductMasterSalesTaxData(mods ...qm.QueryMod) sapProductMasterSalesTaxDatumQuery {
	mods = append(mods, qm.From("`sap_product_master_sales_tax_data`"))
	return sapProductMasterSalesTaxDatumQuery{NewQuery(mods...)}
}

// FindSapProductMasterSalesTaxDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSapProductMasterSalesTaxDatum(ctx context.Context, exec boil.ContextExecutor, product string, country string, taxCategory string, selectCols ...string) (*SapProductMasterSalesTaxDatum, error) {
	sapProductMasterSalesTaxDatumObj := &SapProductMasterSalesTaxDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `sap_product_master_sales_tax_data` where `Product`=? AND `Country`=? AND `TaxCategory`=?", sel,
	)

	q := queries.Raw(query, product, country, taxCategory)

	err := q.Bind(ctx, exec, sapProductMasterSalesTaxDatumObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from sap_product_master_sales_tax_data")
	}

	if err = sapProductMasterSalesTaxDatumObj.doAfterSelectHooks(ctx, exec); err != nil {
		return sapProductMasterSalesTaxDatumObj, err
	}

	return sapProductMasterSalesTaxDatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SapProductMasterSalesTaxDatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sap_product_master_sales_tax_data provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sapProductMasterSalesTaxDatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	sapProductMasterSalesTaxDatumInsertCacheMut.RLock()
	cache, cached := sapProductMasterSalesTaxDatumInsertCache[key]
	sapProductMasterSalesTaxDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			sapProductMasterSalesTaxDatumAllColumns,
			sapProductMasterSalesTaxDatumColumnsWithDefault,
			sapProductMasterSalesTaxDatumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(sapProductMasterSalesTaxDatumType, sapProductMasterSalesTaxDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(sapProductMasterSalesTaxDatumType, sapProductMasterSalesTaxDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `sap_product_master_sales_tax_data` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `sap_product_master_sales_tax_data` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `sap_product_master_sales_tax_data` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, sapProductMasterSalesTaxDatumPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into sap_product_master_sales_tax_data")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.Product,
		o.Country,
		o.TaxCategory,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for sap_product_master_sales_tax_data")
	}

CacheNoHooks:
	if !cached {
		sapProductMasterSalesTaxDatumInsertCacheMut.Lock()
		sapProductMasterSalesTaxDatumInsertCache[key] = cache
		sapProductMasterSalesTaxDatumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SapProductMasterSalesTaxDatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SapProductMasterSalesTaxDatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	sapProductMasterSalesTaxDatumUpdateCacheMut.RLock()
	cache, cached := sapProductMasterSalesTaxDatumUpdateCache[key]
	sapProductMasterSalesTaxDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			sapProductMasterSalesTaxDatumAllColumns,
			sapProductMasterSalesTaxDatumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update sap_product_master_sales_tax_data, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `sap_product_master_sales_tax_data` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, sapProductMasterSalesTaxDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(sapProductMasterSalesTaxDatumType, sapProductMasterSalesTaxDatumMapping, append(wl, sapProductMasterSalesTaxDatumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update sap_product_master_sales_tax_data row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for sap_product_master_sales_tax_data")
	}

	if !cached {
		sapProductMasterSalesTaxDatumUpdateCacheMut.Lock()
		sapProductMasterSalesTaxDatumUpdateCache[key] = cache
		sapProductMasterSalesTaxDatumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q sapProductMasterSalesTaxDatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for sap_product_master_sales_tax_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for sap_product_master_sales_tax_data")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SapProductMasterSalesTaxDatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sapProductMasterSalesTaxDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `sap_product_master_sales_tax_data` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sapProductMasterSalesTaxDatumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in sapProductMasterSalesTaxDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all sapProductMasterSalesTaxDatum")
	}
	return rowsAff, nil
}

var mySQLSapProductMasterSalesTaxDatumUniqueColumns = []string{}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SapProductMasterSalesTaxDatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sap_product_master_sales_tax_data provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sapProductMasterSalesTaxDatumColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLSapProductMasterSalesTaxDatumUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	sapProductMasterSalesTaxDatumUpsertCacheMut.RLock()
	cache, cached := sapProductMasterSalesTaxDatumUpsertCache[key]
	sapProductMasterSalesTaxDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			sapProductMasterSalesTaxDatumAllColumns,
			sapProductMasterSalesTaxDatumColumnsWithDefault,
			sapProductMasterSalesTaxDatumColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			sapProductMasterSalesTaxDatumAllColumns,
			sapProductMasterSalesTaxDatumPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert sap_product_master_sales_tax_data, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`sap_product_master_sales_tax_data`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `sap_product_master_sales_tax_data` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(sapProductMasterSalesTaxDatumType, sapProductMasterSalesTaxDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(sapProductMasterSalesTaxDatumType, sapProductMasterSalesTaxDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for sap_product_master_sales_tax_data")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(sapProductMasterSalesTaxDatumType, sapProductMasterSalesTaxDatumMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for sap_product_master_sales_tax_data")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for sap_product_master_sales_tax_data")
	}

CacheNoHooks:
	if !cached {
		sapProductMasterSalesTaxDatumUpsertCacheMut.Lock()
		sapProductMasterSalesTaxDatumUpsertCache[key] = cache
		sapProductMasterSalesTaxDatumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SapProductMasterSalesTaxDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SapProductMasterSalesTaxDatum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SapProductMasterSalesTaxDatum provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), sapProductMasterSalesTaxDatumPrimaryKeyMapping)
	sql := "DELETE FROM `sap_product_master_sales_tax_data` WHERE `Product`=? AND `Country`=? AND `TaxCategory`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from sap_product_master_sales_tax_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for sap_product_master_sales_tax_data")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q sapProductMasterSalesTaxDatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no sapProductMasterSalesTaxDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sap_product_master_sales_tax_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sap_product_master_sales_tax_data")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SapProductMasterSalesTaxDatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(sapProductMasterSalesTaxDatumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sapProductMasterSalesTaxDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `sap_product_master_sales_tax_data` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sapProductMasterSalesTaxDatumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sapProductMasterSalesTaxDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sap_product_master_sales_tax_data")
	}

	if len(sapProductMasterSalesTaxDatumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SapProductMasterSalesTaxDatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSapProductMasterSalesTaxDatum(ctx, exec, o.Product, o.Country, o.TaxCategory)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SapProductMasterSalesTaxDatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SapProductMasterSalesTaxDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sapProductMasterSalesTaxDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `sap_product_master_sales_tax_data`.* FROM `sap_product_master_sales_tax_data` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sapProductMasterSalesTaxDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SapProductMasterSalesTaxDatumSlice")
	}

	*o = slice

	return nil
}

// SapProductMasterSalesTaxDatumExists checks if the SapProductMasterSalesTaxDatum row exists.
func SapProductMasterSalesTaxDatumExists(ctx context.Context, exec boil.ContextExecutor, product string, country string, taxCategory string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `sap_product_master_sales_tax_data` where `Product`=? AND `Country`=? AND `TaxCategory`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, product, country, taxCategory)
	}
	row := exec.QueryRowContext(ctx, sql, product, country, taxCategory)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if sap_product_master_sales_tax_data exists")
	}

	return exists, nil
}
