// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SapProductMasterProductDescriptionDatum is an object representing the database table.
type SapProductMasterProductDescriptionDatum struct {
	Product            string      `boil:"Product" json:"Product" toml:"Product" yaml:"Product"`
	Language           string      `boil:"Language" json:"Language" toml:"Language" yaml:"Language"`
	ProductDescription null.String `boil:"ProductDescription" json:"ProductDescription,omitempty" toml:"ProductDescription" yaml:"ProductDescription,omitempty"`

	R *sapProductMasterProductDescriptionDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L sapProductMasterProductDescriptionDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SapProductMasterProductDescriptionDatumColumns = struct {
	Product            string
	Language           string
	ProductDescription string
}{
	Product:            "Product",
	Language:           "Language",
	ProductDescription: "ProductDescription",
}

var SapProductMasterProductDescriptionDatumTableColumns = struct {
	Product            string
	Language           string
	ProductDescription string
}{
	Product:            "sap_product_master_product_description_data.Product",
	Language:           "sap_product_master_product_description_data.Language",
	ProductDescription: "sap_product_master_product_description_data.ProductDescription",
}

// Generated where

var SapProductMasterProductDescriptionDatumWhere = struct {
	Product            whereHelperstring
	Language           whereHelperstring
	ProductDescription whereHelpernull_String
}{
	Product:            whereHelperstring{field: "`sap_product_master_product_description_data`.`Product`"},
	Language:           whereHelperstring{field: "`sap_product_master_product_description_data`.`Language`"},
	ProductDescription: whereHelpernull_String{field: "`sap_product_master_product_description_data`.`ProductDescription`"},
}

// SapProductMasterProductDescriptionDatumRels is where relationship names are stored.
var SapProductMasterProductDescriptionDatumRels = struct {
	ProductSapProductMasterGeneralDatum string
}{
	ProductSapProductMasterGeneralDatum: "ProductSapProductMasterGeneralDatum",
}

// sapProductMasterProductDescriptionDatumR is where relationships are stored.
type sapProductMasterProductDescriptionDatumR struct {
	ProductSapProductMasterGeneralDatum *SapProductMasterGeneralDatum `boil:"ProductSapProductMasterGeneralDatum" json:"ProductSapProductMasterGeneralDatum" toml:"ProductSapProductMasterGeneralDatum" yaml:"ProductSapProductMasterGeneralDatum"`
}

// NewStruct creates a new relationship struct
func (*sapProductMasterProductDescriptionDatumR) NewStruct() *sapProductMasterProductDescriptionDatumR {
	return &sapProductMasterProductDescriptionDatumR{}
}

// sapProductMasterProductDescriptionDatumL is where Load methods for each relationship are stored.
type sapProductMasterProductDescriptionDatumL struct{}

var (
	sapProductMasterProductDescriptionDatumAllColumns            = []string{"Product", "Language", "ProductDescription"}
	sapProductMasterProductDescriptionDatumColumnsWithoutDefault = []string{"Product", "Language", "ProductDescription"}
	sapProductMasterProductDescriptionDatumColumnsWithDefault    = []string{}
	sapProductMasterProductDescriptionDatumPrimaryKeyColumns     = []string{"Product", "Language"}
)

type (
	// SapProductMasterProductDescriptionDatumSlice is an alias for a slice of pointers to SapProductMasterProductDescriptionDatum.
	// This should almost always be used instead of []SapProductMasterProductDescriptionDatum.
	SapProductMasterProductDescriptionDatumSlice []*SapProductMasterProductDescriptionDatum
	// SapProductMasterProductDescriptionDatumHook is the signature for custom SapProductMasterProductDescriptionDatum hook methods
	SapProductMasterProductDescriptionDatumHook func(context.Context, boil.ContextExecutor, *SapProductMasterProductDescriptionDatum) error

	sapProductMasterProductDescriptionDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	sapProductMasterProductDescriptionDatumType                 = reflect.TypeOf(&SapProductMasterProductDescriptionDatum{})
	sapProductMasterProductDescriptionDatumMapping              = queries.MakeStructMapping(sapProductMasterProductDescriptionDatumType)
	sapProductMasterProductDescriptionDatumPrimaryKeyMapping, _ = queries.BindMapping(sapProductMasterProductDescriptionDatumType, sapProductMasterProductDescriptionDatumMapping, sapProductMasterProductDescriptionDatumPrimaryKeyColumns)
	sapProductMasterProductDescriptionDatumInsertCacheMut       sync.RWMutex
	sapProductMasterProductDescriptionDatumInsertCache          = make(map[string]insertCache)
	sapProductMasterProductDescriptionDatumUpdateCacheMut       sync.RWMutex
	sapProductMasterProductDescriptionDatumUpdateCache          = make(map[string]updateCache)
	sapProductMasterProductDescriptionDatumUpsertCacheMut       sync.RWMutex
	sapProductMasterProductDescriptionDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var sapProductMasterProductDescriptionDatumBeforeInsertHooks []SapProductMasterProductDescriptionDatumHook
var sapProductMasterProductDescriptionDatumBeforeUpdateHooks []SapProductMasterProductDescriptionDatumHook
var sapProductMasterProductDescriptionDatumBeforeDeleteHooks []SapProductMasterProductDescriptionDatumHook
var sapProductMasterProductDescriptionDatumBeforeUpsertHooks []SapProductMasterProductDescriptionDatumHook

var sapProductMasterProductDescriptionDatumAfterInsertHooks []SapProductMasterProductDescriptionDatumHook
var sapProductMasterProductDescriptionDatumAfterSelectHooks []SapProductMasterProductDescriptionDatumHook
var sapProductMasterProductDescriptionDatumAfterUpdateHooks []SapProductMasterProductDescriptionDatumHook
var sapProductMasterProductDescriptionDatumAfterDeleteHooks []SapProductMasterProductDescriptionDatumHook
var sapProductMasterProductDescriptionDatumAfterUpsertHooks []SapProductMasterProductDescriptionDatumHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SapProductMasterProductDescriptionDatum) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterProductDescriptionDatumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SapProductMasterProductDescriptionDatum) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterProductDescriptionDatumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SapProductMasterProductDescriptionDatum) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterProductDescriptionDatumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SapProductMasterProductDescriptionDatum) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterProductDescriptionDatumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SapProductMasterProductDescriptionDatum) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterProductDescriptionDatumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SapProductMasterProductDescriptionDatum) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterProductDescriptionDatumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SapProductMasterProductDescriptionDatum) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterProductDescriptionDatumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SapProductMasterProductDescriptionDatum) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterProductDescriptionDatumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SapProductMasterProductDescriptionDatum) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range sapProductMasterProductDescriptionDatumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSapProductMasterProductDescriptionDatumHook registers your hook function for all future operations.
func AddSapProductMasterProductDescriptionDatumHook(hookPoint boil.HookPoint, sapProductMasterProductDescriptionDatumHook SapProductMasterProductDescriptionDatumHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		sapProductMasterProductDescriptionDatumBeforeInsertHooks = append(sapProductMasterProductDescriptionDatumBeforeInsertHooks, sapProductMasterProductDescriptionDatumHook)
	case boil.BeforeUpdateHook:
		sapProductMasterProductDescriptionDatumBeforeUpdateHooks = append(sapProductMasterProductDescriptionDatumBeforeUpdateHooks, sapProductMasterProductDescriptionDatumHook)
	case boil.BeforeDeleteHook:
		sapProductMasterProductDescriptionDatumBeforeDeleteHooks = append(sapProductMasterProductDescriptionDatumBeforeDeleteHooks, sapProductMasterProductDescriptionDatumHook)
	case boil.BeforeUpsertHook:
		sapProductMasterProductDescriptionDatumBeforeUpsertHooks = append(sapProductMasterProductDescriptionDatumBeforeUpsertHooks, sapProductMasterProductDescriptionDatumHook)
	case boil.AfterInsertHook:
		sapProductMasterProductDescriptionDatumAfterInsertHooks = append(sapProductMasterProductDescriptionDatumAfterInsertHooks, sapProductMasterProductDescriptionDatumHook)
	case boil.AfterSelectHook:
		sapProductMasterProductDescriptionDatumAfterSelectHooks = append(sapProductMasterProductDescriptionDatumAfterSelectHooks, sapProductMasterProductDescriptionDatumHook)
	case boil.AfterUpdateHook:
		sapProductMasterProductDescriptionDatumAfterUpdateHooks = append(sapProductMasterProductDescriptionDatumAfterUpdateHooks, sapProductMasterProductDescriptionDatumHook)
	case boil.AfterDeleteHook:
		sapProductMasterProductDescriptionDatumAfterDeleteHooks = append(sapProductMasterProductDescriptionDatumAfterDeleteHooks, sapProductMasterProductDescriptionDatumHook)
	case boil.AfterUpsertHook:
		sapProductMasterProductDescriptionDatumAfterUpsertHooks = append(sapProductMasterProductDescriptionDatumAfterUpsertHooks, sapProductMasterProductDescriptionDatumHook)
	}
}

// One returns a single sapProductMasterProductDescriptionDatum record from the query.
func (q sapProductMasterProductDescriptionDatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SapProductMasterProductDescriptionDatum, error) {
	o := &SapProductMasterProductDescriptionDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for sap_product_master_product_description_data")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SapProductMasterProductDescriptionDatum records from the query.
func (q sapProductMasterProductDescriptionDatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (SapProductMasterProductDescriptionDatumSlice, error) {
	var o []*SapProductMasterProductDescriptionDatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SapProductMasterProductDescriptionDatum slice")
	}

	if len(sapProductMasterProductDescriptionDatumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SapProductMasterProductDescriptionDatum records in the query.
func (q sapProductMasterProductDescriptionDatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count sap_product_master_product_description_data rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q sapProductMasterProductDescriptionDatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if sap_product_master_product_description_data exists")
	}

	return count > 0, nil
}

// ProductSapProductMasterGeneralDatum pointed to by the foreign key.
func (o *SapProductMasterProductDescriptionDatum) ProductSapProductMasterGeneralDatum(mods ...qm.QueryMod) sapProductMasterGeneralDatumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`Product` = ?", o.Product),
	}

	queryMods = append(queryMods, mods...)

	query := SapProductMasterGeneralData(queryMods...)
	queries.SetFrom(query.Query, "`sap_product_master_general_data`")

	return query
}

// LoadProductSapProductMasterGeneralDatum allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (sapProductMasterProductDescriptionDatumL) LoadProductSapProductMasterGeneralDatum(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSapProductMasterProductDescriptionDatum interface{}, mods queries.Applicator) error {
	var slice []*SapProductMasterProductDescriptionDatum
	var object *SapProductMasterProductDescriptionDatum

	if singular {
		object = maybeSapProductMasterProductDescriptionDatum.(*SapProductMasterProductDescriptionDatum)
	} else {
		slice = *maybeSapProductMasterProductDescriptionDatum.(*[]*SapProductMasterProductDescriptionDatum)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &sapProductMasterProductDescriptionDatumR{}
		}
		args = append(args, object.Product)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sapProductMasterProductDescriptionDatumR{}
			}

			for _, a := range args {
				if a == obj.Product {
					continue Outer
				}
			}

			args = append(args, obj.Product)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`sap_product_master_general_data`),
		qm.WhereIn(`sap_product_master_general_data.Product in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SapProductMasterGeneralDatum")
	}

	var resultSlice []*SapProductMasterGeneralDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SapProductMasterGeneralDatum")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for sap_product_master_general_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sap_product_master_general_data")
	}

	if len(sapProductMasterProductDescriptionDatumAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ProductSapProductMasterGeneralDatum = foreign
		if foreign.R == nil {
			foreign.R = &sapProductMasterGeneralDatumR{}
		}
		foreign.R.ProductSapProductMasterProductDescriptionData = append(foreign.R.ProductSapProductMasterProductDescriptionData, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Product == foreign.Product {
				local.R.ProductSapProductMasterGeneralDatum = foreign
				if foreign.R == nil {
					foreign.R = &sapProductMasterGeneralDatumR{}
				}
				foreign.R.ProductSapProductMasterProductDescriptionData = append(foreign.R.ProductSapProductMasterProductDescriptionData, local)
				break
			}
		}
	}

	return nil
}

// SetProductSapProductMasterGeneralDatum of the sapProductMasterProductDescriptionDatum to the related item.
// Sets o.R.ProductSapProductMasterGeneralDatum to related.
// Adds o to related.R.ProductSapProductMasterProductDescriptionData.
func (o *SapProductMasterProductDescriptionDatum) SetProductSapProductMasterGeneralDatum(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SapProductMasterGeneralDatum) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `sap_product_master_product_description_data` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"Product"}),
		strmangle.WhereClause("`", "`", 0, sapProductMasterProductDescriptionDatumPrimaryKeyColumns),
	)
	values := []interface{}{related.Product, o.Product, o.Language}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.Product = related.Product
	if o.R == nil {
		o.R = &sapProductMasterProductDescriptionDatumR{
			ProductSapProductMasterGeneralDatum: related,
		}
	} else {
		o.R.ProductSapProductMasterGeneralDatum = related
	}

	if related.R == nil {
		related.R = &sapProductMasterGeneralDatumR{
			ProductSapProductMasterProductDescriptionData: SapProductMasterProductDescriptionDatumSlice{o},
		}
	} else {
		related.R.ProductSapProductMasterProductDescriptionData = append(related.R.ProductSapProductMasterProductDescriptionData, o)
	}

	return nil
}

// SapProductMasterProductDescriptionData retrieves all the records using an executor.
func SapProductMasterProductDescriptionData(mods ...qm.QueryMod) sapProductMasterProductDescriptionDatumQuery {
	mods = append(mods, qm.From("`sap_product_master_product_description_data`"))
	return sapProductMasterProductDescriptionDatumQuery{NewQuery(mods...)}
}

// FindSapProductMasterProductDescriptionDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSapProductMasterProductDescriptionDatum(ctx context.Context, exec boil.ContextExecutor, product string, language string, selectCols ...string) (*SapProductMasterProductDescriptionDatum, error) {
	sapProductMasterProductDescriptionDatumObj := &SapProductMasterProductDescriptionDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `sap_product_master_product_description_data` where `Product`=? AND `Language`=?", sel,
	)

	q := queries.Raw(query, product, language)

	err := q.Bind(ctx, exec, sapProductMasterProductDescriptionDatumObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from sap_product_master_product_description_data")
	}

	if err = sapProductMasterProductDescriptionDatumObj.doAfterSelectHooks(ctx, exec); err != nil {
		return sapProductMasterProductDescriptionDatumObj, err
	}

	return sapProductMasterProductDescriptionDatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SapProductMasterProductDescriptionDatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sap_product_master_product_description_data provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sapProductMasterProductDescriptionDatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	sapProductMasterProductDescriptionDatumInsertCacheMut.RLock()
	cache, cached := sapProductMasterProductDescriptionDatumInsertCache[key]
	sapProductMasterProductDescriptionDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			sapProductMasterProductDescriptionDatumAllColumns,
			sapProductMasterProductDescriptionDatumColumnsWithDefault,
			sapProductMasterProductDescriptionDatumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(sapProductMasterProductDescriptionDatumType, sapProductMasterProductDescriptionDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(sapProductMasterProductDescriptionDatumType, sapProductMasterProductDescriptionDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `sap_product_master_product_description_data` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `sap_product_master_product_description_data` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `sap_product_master_product_description_data` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, sapProductMasterProductDescriptionDatumPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into sap_product_master_product_description_data")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.Product,
		o.Language,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for sap_product_master_product_description_data")
	}

CacheNoHooks:
	if !cached {
		sapProductMasterProductDescriptionDatumInsertCacheMut.Lock()
		sapProductMasterProductDescriptionDatumInsertCache[key] = cache
		sapProductMasterProductDescriptionDatumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SapProductMasterProductDescriptionDatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SapProductMasterProductDescriptionDatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	sapProductMasterProductDescriptionDatumUpdateCacheMut.RLock()
	cache, cached := sapProductMasterProductDescriptionDatumUpdateCache[key]
	sapProductMasterProductDescriptionDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			sapProductMasterProductDescriptionDatumAllColumns,
			sapProductMasterProductDescriptionDatumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update sap_product_master_product_description_data, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `sap_product_master_product_description_data` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, sapProductMasterProductDescriptionDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(sapProductMasterProductDescriptionDatumType, sapProductMasterProductDescriptionDatumMapping, append(wl, sapProductMasterProductDescriptionDatumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update sap_product_master_product_description_data row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for sap_product_master_product_description_data")
	}

	if !cached {
		sapProductMasterProductDescriptionDatumUpdateCacheMut.Lock()
		sapProductMasterProductDescriptionDatumUpdateCache[key] = cache
		sapProductMasterProductDescriptionDatumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q sapProductMasterProductDescriptionDatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for sap_product_master_product_description_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for sap_product_master_product_description_data")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SapProductMasterProductDescriptionDatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sapProductMasterProductDescriptionDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `sap_product_master_product_description_data` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sapProductMasterProductDescriptionDatumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in sapProductMasterProductDescriptionDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all sapProductMasterProductDescriptionDatum")
	}
	return rowsAff, nil
}

var mySQLSapProductMasterProductDescriptionDatumUniqueColumns = []string{}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SapProductMasterProductDescriptionDatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no sap_product_master_product_description_data provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(sapProductMasterProductDescriptionDatumColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLSapProductMasterProductDescriptionDatumUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	sapProductMasterProductDescriptionDatumUpsertCacheMut.RLock()
	cache, cached := sapProductMasterProductDescriptionDatumUpsertCache[key]
	sapProductMasterProductDescriptionDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			sapProductMasterProductDescriptionDatumAllColumns,
			sapProductMasterProductDescriptionDatumColumnsWithDefault,
			sapProductMasterProductDescriptionDatumColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			sapProductMasterProductDescriptionDatumAllColumns,
			sapProductMasterProductDescriptionDatumPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert sap_product_master_product_description_data, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`sap_product_master_product_description_data`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `sap_product_master_product_description_data` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(sapProductMasterProductDescriptionDatumType, sapProductMasterProductDescriptionDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(sapProductMasterProductDescriptionDatumType, sapProductMasterProductDescriptionDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for sap_product_master_product_description_data")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(sapProductMasterProductDescriptionDatumType, sapProductMasterProductDescriptionDatumMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for sap_product_master_product_description_data")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for sap_product_master_product_description_data")
	}

CacheNoHooks:
	if !cached {
		sapProductMasterProductDescriptionDatumUpsertCacheMut.Lock()
		sapProductMasterProductDescriptionDatumUpsertCache[key] = cache
		sapProductMasterProductDescriptionDatumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SapProductMasterProductDescriptionDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SapProductMasterProductDescriptionDatum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SapProductMasterProductDescriptionDatum provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), sapProductMasterProductDescriptionDatumPrimaryKeyMapping)
	sql := "DELETE FROM `sap_product_master_product_description_data` WHERE `Product`=? AND `Language`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from sap_product_master_product_description_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for sap_product_master_product_description_data")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q sapProductMasterProductDescriptionDatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no sapProductMasterProductDescriptionDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sap_product_master_product_description_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sap_product_master_product_description_data")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SapProductMasterProductDescriptionDatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(sapProductMasterProductDescriptionDatumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sapProductMasterProductDescriptionDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `sap_product_master_product_description_data` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sapProductMasterProductDescriptionDatumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from sapProductMasterProductDescriptionDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for sap_product_master_product_description_data")
	}

	if len(sapProductMasterProductDescriptionDatumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SapProductMasterProductDescriptionDatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSapProductMasterProductDescriptionDatum(ctx, exec, o.Product, o.Language)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SapProductMasterProductDescriptionDatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SapProductMasterProductDescriptionDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sapProductMasterProductDescriptionDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `sap_product_master_product_description_data`.* FROM `sap_product_master_product_description_data` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, sapProductMasterProductDescriptionDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SapProductMasterProductDescriptionDatumSlice")
	}

	*o = slice

	return nil
}

// SapProductMasterProductDescriptionDatumExists checks if the SapProductMasterProductDescriptionDatum row exists.
func SapProductMasterProductDescriptionDatumExists(ctx context.Context, exec boil.ContextExecutor, product string, language string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `sap_product_master_product_description_data` where `Product`=? AND `Language`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, product, language)
	}
	row := exec.QueryRowContext(ctx, sql, product, language)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if sap_product_master_product_description_data exists")
	}

	return exists, nil
}
